### ISSUE TITLE
America/Montreal is missing from zone.tab

### ISSUE THREAD

**Issue by guyboertje** [tzinfo/tzinfo-data#2]
I have just raised an issue on the tz repo

https://github.com/eggert/tz/issues/4

Seems like a revert was not completely done.  Is there any way it can be added back into zone.tab and the ruby side too?

**Comment by kashifshamaz21** [comment]
After scratching my head for quite a well, found this *very, very* useful thread. Timezones are a complete mess! The `checktab.awk` file has this following line, since a commit done in 2013:
```	
# A special (and we hope temporary) case.
	tztab["America/Montreal"] = 1
```
commit hash for more reference: https://github.com/eggert/tz/commit/2022cddf08b6d97e34a41010ca145545de7182b2

As mentioned above by @guyboertje , any application that provides utility functions to return list of zones of countries, will have to keep this explicit mapping of `America/Montreal => Canada`.
Just seems so hacky! 
And the latest version(2014j) of tz data, has a few more lines like these:
```
# Some more special cases; these are zones that should probably
# be turned into links.
	if (zone_table == "zone1970.tab") {
	          tztab["America/Antigua"] = 1
		  tztab["America/Cayman"] = 1
		  tztab["Pacific/Midway"] = 1
		  tztab["Pacific/Saipan"] = 1
	}
```
But atleast for these zones, they have an entry in the `zone.tab` file.
