### ISSUE TITLE
2015f  is out

### ISSUE THREAD

**Issue by urkle** [tzinfo/tzinfo-data#6]
This has the new adjustments to the North Korean Timezone change among other things.

http://mm.icann.org/pipermail/tz-announce/2015-August/000033.html

**Comment by philr** [comment]
@urkle I intend to release an update to tzinfo-data later today.

Please note that there is no need to raise issues for TZ database updates like this in the future. Each (future) release of the TZ database will be packaged into a tzinfo-data release.

**Comment by philr** [comment]
Version 1.2015.6 of tzinfo-data has now been released (based on version 2015f of the TZ database).

**Comment by conorliv** [comment]
@philr I'm trying to decide if I'm going to use this gem as a tz data source or manually include the IANA tables. I see a few benefits of using this gem:

- Plug-n-play integration with the tzinfo gem
- Updating this gem would be easier than adding new IANA tables manually

However, I'm leaning towards manually including the IANA tables for the following reason:

- if I use this gem I depend on it's maintainers to have accurate tz info in my application

Historically it seems like the tables have been updated very diligently, and I could fork this gem and update the tables myself if needed. But at that point it may just be easier to use IANA tables manually.

Do you have any additional thoughts on this decision? I posted this here because it relates to this issue.

**Comment by urkle** [comment]
@conorliv IMHO, the best approach would be for clean documentation to be provided on how to update this gem so that users can more easily submit pull requests to make it easier on the developer to maintain.   Then you can simply update a fork and submit a PR so that everyone benefits instead of just your application.  Especially since this is a VERY commonly used gem for timezone data in ruby applications.

**Comment by philr** [comment]
@conorliv It is my intention that a new version of the tzinfo-data gem will be released soon after each IANA Time Zone Database release is made.

If you want to update tzinfo-data yourself, you can extract the tzdata files from an IANA Time Zone Database release into the data directory and then run `rake build_tz_modules`.

TZInfo can obtain data from either the tzinfo-data gem or from zoneinfo files (as created by the zic tool included in the Time Zone Database tzcode releases). You can use the [`TZInfo::DataSource.set`](http://www.rubydoc.info/gems/tzinfo/TZInfo%2FDataSource.set) method to specify which source of data should be used.

@urkle Because TZInfo will by default use the system zoneinfo files as a data source, the tzinfo-data gem is not as commonly used as tzinfo. For example, the Rails [default Gemfile](https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/Gemfile) only specifies tzinfo-data for the Windows and JRuby platforms (because Windows doesn't include a zoneinfo directory).

Regarding pull requests for data updates, at the moment, it is quicker and easier for me to process new tzdata releases than it is to verify and merge a pull request. I am therefore not interested in receiving pull requests for new Time Zone Database releases.

**Comment by conorliv** [comment]
@urkle @philr Thanks for your quick responses. I appreciate your insights and have decided to use the tzinfo-data gem for the following reasons:

-  Plug-n-play integration with the tzinfo gem
- Updating this gem would be easier than adding new IANA tables manually
- fact that tzinfo has 91m downloads means someone will most likely notice if tzinfo-data gets out of date and open an issue here. the last time this happened the maintainer responded and released a new version of the gem on the same day
- maintainer explained how to update the timetables in tzinfo-data if needed
- maintainer clearly expressed intention to keep tzinfo-data up to date
